---
- hosts: all
  become: true
  tasks:
  - name:
    yum:
     name: java
     state: latest
  - name: Display JavaPackageVersion
    shell:
     name: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
     register: javaVersion
  - name:
    debug:
     var: javaVersion.stdout
...