FROM ubuntu:latest
WORKDIR /opt/jenkins
RUN apt update && apt install -y wget openjdk-17-jre-headless
RUN wget https://updates.jenkins.io/latest/jenkins.war
EXPOSE 8080
#COPY jenkins.war jenkins.war
ENV JENKINS_HOME=/var/jenkins_data
ENTRYPOINT ["java" , "-jar" , "jenkins.war"]