---
- hosts: all
  become: true
  tasks: 
  - name: 
    user: 
     name: "{{item.name}}"
     create_home: "{{item.cratehome}}"
    with_items: 
     - {'name': 'umair', 'createhome': no}
     - {'name': 'armu', 'createhome': no}
     - {'name': 'navab', 'createhome': yes}
     - {'name': 'avesh', 'createhome': yes}
...