---
- hosts: all
  become: true
  tasks: 
  - name: Install Apache HTTP Server
    tags:
     - install 
    yum: 
     name: httpd
     state: latest
  - name: 
    tags:
     - copy
    copy: 
     src: index.html
     dest: /var/www/html/index.html
  - name: Start the Apache Server 
    tags: 
    - start
    service: 
     name: httpd
     state: started
     enabled: true
...