---
- hosts: all
  become: true
  tasks:
    - name: Check if Git is installed
      shell: git --version
      register: git_version
      ignore_errors: true

    - name: Display whether Git is installed or not
      when: git_version.rc != 0
      debug:
        msg: "Git not installed"

    - name: Install Git
      when: git_version.rc != 0
      yum:
        name: git
        state: present

    - name: Get Git version
      shell: git --version
      register: git_version_output

    - name: Display Git version
      debug:
        msg: "Git is installed and the version is {{ git_version_output.stdout }}"
...